name: richarddavy
favicon: null
layout_spectrum: 0.71821
typography_spectrum: 0.6057309585157782
title: Little nuggets of joy - the findings and musings of a digital creative.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.739786755759269
  lightness: 0.049278801307082176
  saturation: 0.11027256515808403
  rhythmicContrast: 0.5161210899241269
purpose: []
